<?php
/**
 * @author Tridhyatech Team
 * @copyright Copyright (c) 2019 Tridhyatech (https://www.tridhya.com/)
 * @package Tridhyatech_Slider
 */
   $tridhyaHelper = $this->helper('Tridhyatech\Slider\Helper\Data');
   $sliderMode = $tridhyaHelper->getConfig('slider/slide/sliderenabledisable');
 ?>
<?php if($sliderMode == "1"): ?>
<?php
   $slider = $block->getSliderCollectionForProducts();
   $url = $block->getBaseUrl();
   $display = $tridhyaHelper->getConfig('slider/sliderconfiguration/display');
   $delay = $tridhyaHelper->getConfig('slider/sliderconfiguration/delay');
   $displayTitles = $tridhyaHelper->getConfig('slider/sliderconfiguration/display_titles');
   $nextPrevious = $tridhyaHelper->getConfig('slider/sliderconfiguration/next_previous');
   $autoSlide = $tridhyaHelper->getConfig('slider/sliderconfiguration/auto_slide');
   $autoplay_hoverpause = $tridhyaHelper->getConfig('slider/sliderconfiguration/autoplay_hoverpause');
   $contentSlide = $tridhyaHelper->getConfig('slider/sliderconfiguration/content_slide');
   $rightContentMode = $tridhyaHelper->getConfig('slider/sliderconfiguration/right_content');
   $height = $tridhyaHelper->getConfig('slider/sliderconfiguration/height');
   ?>
<?php if($slider->getSize()):?>
 <div class="tridhya-slider">
    <div class="owl-carousel" id="banner_slider" style="height: <?php echo $height.'px'; ?>;">
      <?php $i=0; foreach ($slider as $item): $div = "content_slider";  $rightDiv = "slider-rightcontent"; ?>
        <div class="item">
          <?php $imageicon = ''; $title = ''; $content = ''; $rightContent = ''; $video = '';
            if (!empty($item->getIcon())) { $imageicon = $item->getIcon(); }
            if (!empty($item->getTitle())){ $title = $item->getTitle(); }
            if (!empty($item->getContent())){ $content = $item->getContent(); }
            if (!empty($item->getRightcontent())){ $rightContent = $item->getRightcontent(); }
            if ($item->getVideo()) { $video = $item->getVideo(); }
          ?>
          <?php if (!empty($imageicon)) { ?>
          <div class="banner-image">
            <?php $sliderUrl = ''; if (!empty($item->getSliderurl())){ $sliderUrl = $item->getSliderurl(); ?>
              <a href="<?php echo $sliderUrl; ?>">
                <img src="<?php echo $block->getImageUrl($imageicon); ?>" alt="<?php echo $title; ?>"/>
              </a>
            <?php }?>
            <?php  if (empty($sliderUrl)) { ?>
                <img src="<?php echo $block->getImageUrl($imageicon); ?>" alt="<?php echo $title; ?>"/>
            <?php } ?>
          </div>
          <?php } ?>
            <?php if(!empty($video)) { ?>
          <div id="player" class="item-video">
             <iframe class="embed-responsive-item" src="<?php echo $video; ?>"></iframe>
          </div>
            <?php } ?>
            <?php if ($displayTitles == 0 && $contentSlide == 0) {
                    $div = "content_slider content_disabled";
                  }  elseif (empty($title) && empty($content)) {
                    $div = "content_slider content_disabled";
                  }  elseif (!empty($video)) {
                    $div = "content_slider content_disabled";
                  }  elseif ($displayTitles == 0 && empty($content)) {
                    $div = "content_slider content_disabled";
                  }  elseif ($contentSlide == 0 && empty($title)) {
                    $div = "content_slider content_disabled";
                  }
            ?>
          <div class="<?php echo $div ?>">
            <?php if ($displayTitles == 1) : ?>
              <span class="banner-title">
                <h4>
                  <?php echo $item->getTitle(); ?>
                </h4>
              </span>
            <?php endif; ?>
            <?php if($contentSlide == 1) : ?>
              <span class="banner-content">
                  <?php echo $content; ?>
              </span>
            <?php endif; ?>
          </div>
            <?php if ($rightContentMode == 0 ) {
                    $rightDiv = "slider-rightcontent-disabled"; }
                  elseif (empty($rightContent)) {
                    $rightDiv = "slider-rightcontent-disabled"; }
                  elseif (!empty($video)) {
                    $rightDiv = "slider-rightcontent-disabled"; }
            ?>
          <div class="<?php echo $rightDiv ?>">
                <?php echo $rightContent; ?>
          </div>
        </div>
       <?php $i++; 
       if ($i == ($display)) break;
     endforeach;?>
   </div>
</div>
<?php $nav = 'false'; if($nextPrevious == 1):  $nav = 'true'; ?>
<?php endif; ?>
<?php $auto = 'false'; if($autoSlide == 1): $auto = 'true'; ?>
<?php endif; ?>
<?php $autoHoverpause = 'false'; if($autoplay_hoverpause == 1): $autoHoverpause = 'true'; ?>
<?php endif; ?>
<?php $del = '4000'; if(!empty($delay) && ($autoSlide == 1)): $del = $delay; ?>
<?php endif; ?>
<?php $noOfSlider = '1'; if(!empty($display)): $noOfSlider = $display; ?>
<?php endif; ?>
<?php $navDots = 'false'; if ($slider->getSize()>1): $navDots = 'true'; ?>
<?php endif; ?>
<script>
   require(['jquery', 'Tridhyatech_Slider/js/owl.carousel.min'], function ($) {
       $('#banner_slider').owlCarousel({
           loop:true,
           center:true,
           margin:0,
           nav:<?php echo $nav; ?>,
           dots:<?php echo $navDots; ?>,
           autoplayTimeout:<?php echo $del; ?>,
           items:1,
           autoplay:<?php echo $auto; ?>,
           autoplayHoverPause: <?php echo $autoHoverpause; ?>,
           video:true
       });
   });
</script>
<?php endif; ?>
<?php endif; ?>
