<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title    = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' . $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
if($product)
{
echo $url= $product->getBaseurl();
$value = $product->getAttributeText('Brand_Name');
if($value)
{ 
 foreach($value as $data)
{?> 
<!-- brand class  -->


<a  href="
<?php   $brand_url=$url."".$data;
echo $brand_url = str_replace(' ', '', $brand_url);  ?>.html" class="<?php echo $data;?>" title="<?php echo $data;?>"  ><?php  echo $data;?></a>
 
  <?php  }
}
}

?>



<?php if ($title): ?>
    <div class="page-title-wrapper<?php /* @escapeNotVerified */
    echo $cssClass; ?>">
        <h1 class="page-title"
            <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */
            echo $block->getId(); ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?php /* @escapeNotVerified */
                echo $block->getAddBaseAttributeAria(); ?>"
            <?php endif; ?>>
            <?php echo $t= $block->getId(); ?>
            <?php /* @escapeNotVerified */
            echo $title
             ?>
        </h1>
        
        <?php echo $block->getChildHtml(); ?>
    </div>
<?php endif; ?>

