<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Market\Helper\Data');
$homeStyle          = $_config->getThemeLayout('home_style');

//get product label helper
$productLabelHelper = $this->helper(Sparsh\ProductLabel\Helper\ProductLabelHelper::class);
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="toolbar-top">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode        = 'grid';
        $image           = 'category_page_grid';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode        = 'list';
        $image           = 'category_page_list';
        $showDescription = true;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-product products wrapper product-card <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>

        <?php if ($viewMode == 'grid') { ?>
            <ol class="products list items product-items row">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
                        $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <div class="image-grid">
                                <a href="<?= /* @escapeNotVerified */
                                $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                </a>
                            </div>


                            <!--LABEL PRODUCT-->
                            <?php
                            $orgprice = (float)$_product->getPrice();
                            $fnPrice  = (float)$_product->getFinalPrice();
                            $getSpecialPrice = (float)$_product->getSpecialPrice();

                            if ($_config->getAdvanced('show_salelabel')) {
                                if ($fnPrice < $orgprice) { ?>
                                    <div class="label-product label-sale">
									<span class="sale-product-icon">
										<?php echo __('Sale'); ?>
									</span>
                                    </div>
                                <?php }
                            }
                            ?>

                            <?php
                            $now      = date("Y-m-d");
                            $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                            $newsTo   = substr($_product->getNewsToDate(), 0, 10);


                            if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                    <div class="label-product label-new">
                                        <span class="new-product-icon"><?php echo __('New'); ?></span>
                                    </div>
                                <?php }
                            } ?>
                            <!--END LABEL PRODUCT-->

                            <div class="product details product-item-details">
                                <small><?php $_getMyAttr = $_product->getResource()->getAttribute('Brand_Name');

// Get Value
if($_getMyAttr){ ?>

    <a href="<?= /* @escapeNotVerified */
    $_product->getProductUrl() ?>" 
       ><?php echo $branname = $_getMyAttr->getFrontend()->getValue($_product);
  ?>   </a>


<?php }?></small>
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
                                       $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                               
                                <?= $block->getProductDetailsHtml($_product) ?>
                                <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                            <?= /* @escapeNotVerified */
                                            $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= /* @escapeNotVerified */
                                            $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                            $_productNameStripped ?>"
                                               class="action more"><?= /* @escapeNotVerified */
                                                __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                               
                                <div class="short-description">
                                    <p><?php         echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ; ?></p>
                                </div>
<!-- product icons -->

<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $storeurl=$storeManager->getStore()->getBaseUrl();

 

$_getMyAttr = $_product->getResource()->getAttribute('product_icon');

if($_getMyAttr)

{

  $attrTestValue = $_getMyAttr->getFrontend()->getValue($_product);
  $icon= explode( ',' , $attrTestValue ) ;

  foreach($icon as $icon_label)
  {?> 
  <!-- icon class  -->
  <a  href="
 <?php   $icon_url=$storeurl."".$icon_label;
 
 echo $iconurl = str_replace(' ', '', $icon_url);  ?>.html" class="<?php echo $icon_label;?>" title="<?php echo $icon_label;?>"  ><?php  echo $icon_label;?></a>
    
    <?php  } 

  }
?>



<!-- Offer label -->
<?php 
$productLabelType = $productLabelHelper->getProductLabelType($_product);
if (!empty($productLabelType)) {
                       if ($productLabelType == 'text') {
                           $productLabel = $productLabelHelper->getProductLabel($_product);
                           $productLabelShape = $productLabelHelper->getProductLabelShape($_product);
                           if ($productLabel && $productLabelShape) { ?>
                           <!-- offer label -->
                               <span class="">
                                   <?= $block->escapeHtml($productLabel); ?> 
                                 
                               </span>
                           <?php }
                       } elseif ($productLabelType == 'image') {
                           $productLabelImage = $productLabelHelper->getProductLabelImage($_product);
                           if ($productLabelImage) { ?>
                           <!-- offer image label -->
                               <div class="">
                                   <img src="<?= /* @noEscape */ $productLabelHelper->getProductMediaUrl() . $productLabelImage; ?>">
                               </div>
                           <?php }
                       }
                   }

?>                                
                            </div>

                            <div class="right-card-block">
                           <div class="price-block">
                           <?= /* @escapeNotVerified */
                                $block->getProductPrice($_product) ?>
                               
                                    
                                    <?php 


$percentage = 0;
if ($orgprice > $fnPrice)
 {
    $percentage = ($orgprice - $fnPrice) * 100 / $orgprice;
    $saveprice = ($orgprice - $fnPrice); 
}

if ($percentage) 
{
    echo '<div class="percentage-block"><span class="discount_amount">'.(int)$percentage.'</span><span class="price_percentage">%</span></div>' ; 
    // echo "";
if($saveprice)
{   
    echo '<div class="save-amount"><span class="price_save">Save!</span> <span class="price_saved_final">'.$saveprice.'</span></div>'; 
    // echo "<span class='price_save'>Save!</span>";
}
  
}
// (int)




                                 ?>
                                    
                           </div>
                            <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                      action="<?= /* @NoEscape */
                                                      $postParams['action'] ?>" method="post">
                                                      
  <!-- attribute value dropdown  -->
                                                      <?php                                                  
$_objectManager= \Magento\Framework\App\ObjectManager::getInstance();
$productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
$productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($_product);
if (!empty($productAttributeOptions)) { //check if product has custom options. If it doesn't go to the next product
    foreach($productAttributeOptions as $productAttributeOption){
        ?>
        <p><span><?php echo $productAttributeOption['label']; ?></span></p>
        <select name="super_attribute[<?php echo $productAttributeOption['attribute_id'] ?>]" data-selector="super_attribute[151]" data-validate="{required:true}" id="attribute151" class="super-attribute-select" aria-required="true">
            <?php
            foreach($productAttributeOption['values'] as $configure_option)
            {
                ?>
                <option value="<?php echo $configure_option['value_index']; ?>"><?php echo $configure_option['label'] ?></option>
                <?php
            }
            ?>

        </select>
        <?php
    }
}

?>

 <?php 


$product_Id = $_product->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockInfo = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($product_Id);
$stockqty = (int)$stockInfo->getQty();

$qty = (int)$stockInfo->getMaxSaleQty();
//echo $qty;

?>

   <p>Qty</p>       
            <select name="qty" id="qty" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" 
                   class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                   <?php $i = 1 ; ?>
                    <?php 
                        
                            while( $i <= $qty) { ?>
                                <option value="<?php echo $i; ?>"><?php echo  $i; ?></option>
                                <?php $i++; 
                                }?>
                       

                    </div>
            </select>

 
   
                                                      
                                                      
                                                    <input type="hidden" name="product"
                                                           value="<?= /* @escapeNotVerified */
                                                           $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @escapeNotVerified */
                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */
                                                            __('Add to Cart') ?></span>
                                                    </button>
                                                    <?php
                                           if($_product->isAvailable())
                                            
                                            {
                                                echo"<div class='in-stock'>In stock. Immediate delivery.</div>";
                                            }
                                            
                                            ?>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */
                                                            __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                            __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>

                                        
                                    </div>
                                 
                                </div>
                            </div>
                            
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php } else { ?>
            <ol class="products list items product-items">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-list">
                            <div class="item-inner">
                                <div class="box-image-list">
                                    <?php $productImage = $block->getImage($_product, $image); ?>

                                    <!--LABEL PRODUCT-->
                                    <?php
                                    $orgprice = (float)$_product->getPrice();
                                    $fnPrice  = (float)$_product->getFinalPrice();

                                    if ($_config->getAdvanced('show_salelabel')) {
                                        if ($fnPrice < $orgprice) { ?>
                                            <div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo __('Sale'); ?>
												</span>
                                            </div>
                                        <?php }
                                    }
                                    ?>

                                    <?php
                                    $now      = date("Y-m-d");
                                    $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                                    $newsTo   = substr($_product->getNewsToDate(), 0, 10);


                                    if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                                        if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                            <div class="label-product label-new">
                                                <span class="new-product-icon"><?php echo __('New'); ?></span>
                                            </div>
                                        <?php }
                                    } ?>
                                    <!--END LABEL PRODUCT-->

                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>

                                </div>

                                <small><?php $_getMyAttr = $_product->getResource()->getAttribute('Brand_Name');

// Get Value
if($_getMyAttr){ ?>

    <a href="<?= /* @escapeNotVerified */
    $_product->getProductUrl() ?>" 
       ><?php echo $branname = $_getMyAttr->getFrontend()->getValue($_product);
  ?>   </a>


<?php }?></small>




                                <div class="product details product-item-details box-info-list">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <h2 class="product name product-item-name product-name">
                                        <a class="product-item-link" href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </h2>

                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                  

                                    <div class="product-item-inner">
                                        <?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
                                                <?php /* @escapeNotVerified */
                                                echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */
                                                echo $_product->getProductUrl() ?>"
                                                   title="<?php /* @escapeNotVerified */
                                                   echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */
                                                    echo __('Learn More') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>

                                    
                                </div>
                                <div class="right-card-block">
                                    <div class="price-block">
                                    <?php /* @escapeNotVerified */
                                    echo $block->getProductPrice($_product) ?>
                                    
                                    
                                    
                                    
                                    
                                    <?php 
$percentage = 0;
if ($orgprice > $fnPrice)
 {
    $percentage = ($orgprice - $fnPrice) * 100 / $orgprice;
    $saveprice = ($orgprice - $fnPrice); 
}

if ($percentage) 
{
    echo '<div class="percentage-block"><span class="discount_amount">'.(int)$percentage.'</span><span class="price_percentage">%</span></div>' ; 
    // echo "";
if($saveprice)
{   
    echo '<div class="save-amount"><span class="price_save">Save!</span> <span class="price_saved_final">'.$saveprice.'</span></div>'; 
    // echo "<span class='price_save'>Save!</span>";
}
  
}



 ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                    </div>
                                <div class="bottom-action">

<!-- product icons -->

<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $storeurl=$storeManager->getStore()->getBaseUrl();

$_getMyAttr = $_product->getResource()->getAttribute('product_icon');


  $attrTestValue = $_getMyAttr->getFrontend()->getValue($_product);
  $icon= explode( ',' , $attrTestValue ) ;

  foreach($icon as $icon_label)
  {?> 
  <!-- icon class  -->
  <a  href="
 <?php   $icon_url=$storeurl."".$icon_label;
 
 echo $iconurl = str_replace(' ', '', $icon_url);  ?>.html" class="<?php echo $icon_label;?>" title="<?php echo $icon_label;?>"  ><?php  echo $icon_label;?></a>
    
    <?php  } 


?>



<!-- Offer label -->
<?php 
$productLabelType = $productLabelHelper->getProductLabelType($_product);
if (!empty($productLabelType)) {
                       if ($productLabelType == 'text') {
                           $productLabel = $productLabelHelper->getProductLabel($_product);
                           $productLabelShape = $productLabelHelper->getProductLabelShape($_product);
                           if ($productLabel && $productLabelShape) { ?>
                           <!-- offer label -->
                               <span class="">
                                   <?= $block->escapeHtml($productLabel); ?> 
                                 
                               </span>
                           <?php }
                       } elseif ($productLabelType == 'image') {
                           $productLabelImage = $productLabelHelper->getProductLabelImage($_product);
                           if ($productLabelImage) { ?>
                           <!-- offer image label -->
                               <div class="">
                                   <img src="<?= /* @noEscape */ $productLabelHelper->getProductMediaUrl() . $productLabelImage; ?>">
                               </div>
                           <?php }
                       }
                   }

?>                                





                                    <div class="bottom-action">
                                        <?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                echo $postParams['action']; ?>" method="post">


<?php
$_objectManager= \Magento\Framework\App\ObjectManager::getInstance();
$productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
$productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($_product);
if (!empty($productAttributeOptions)) { //check if product has custom options. If it doesn't go to the next product
    foreach($productAttributeOptions as $productAttributeOption){
        ?>
        <p><span><?php echo $productAttributeOption['label']; ?></span></p>
        <select name="super_attribute[<?php echo $productAttributeOption['attribute_id'] ?>]" data-selector="super_attribute[151]" data-validate="{required:true}" id="attribute151" class="super-attribute-select" aria-required="true">
            <?php
            foreach($productAttributeOption['values'] as $configure_option)
            {
                ?>
                <option value="<?php echo $configure_option['value_index']; ?>"><?php echo $configure_option['label'] ?></option>
                <?php
            }
            ?>

        </select>
        <?php
    }
}
?>
    <?php 


$product_Id = $_product->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockInfo = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($product_Id);
$stockqty = (int)$stockInfo->getQty();

$MaxSaleQty = (int)$stockInfo->getMaxSaleQty();
//echo $qty;

?>

    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>               
            <select name="qty" id="qty" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" 
                   class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                   <?php $i = 1 ; ?>
                    <?php 
                        
                            while( $i <= $MaxSaleQty) { ?>
                                <option value="<?php echo $i; ?>"><?php echo  $i; ?></option>
                                <?php $i++; 
                                }?>
                       

                    </div>
            </select>


            <br>

                                                    <input type="hidden" name="product"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */
                                                    echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart btn-action btn-cart">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                    </button>
                                                    <?php
                                                    if($_product->isAvailable())
                                            
                                            {
                                                echo"<div class='in-stock'>In stock. Immediate delivery.</div>";
                                            }
                                            
                                            ?>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                            echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
                                                            echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php } ?>

                                      
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php } ?>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        

        

        </script>
    <?php endif; ?>
<?php endif; ?>


