<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product              = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper         = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_config               = $this->helper('Sm\Market\Helper\Data');
?>
<?php

if($product_brand = $this->getProduct()->getAttributeText('product_brand')):
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId($product_brand)
->toHtml();
endif;
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $storeurl=$storeManager->getStore()->getBaseUrl();
 ?>
<a href="#description">view more details</a>
<div class="ytp-cued-thumbnail-overlay-image" id="description" ><a href="#description">video details</a>
</div>

<?php

$_getMyAttr = $_product->getResource()->getAttribute('product_icon');

if($_getMyAttr)

{
   $icon_attributeLabel=$_getMyAttr->getStoreLabel($_product);
?>
<span><?php echo $icon_attributeLabel; ?></span><br>
<?php
  $attrTestValue = $_getMyAttr->getFrontend()->getValue($_product);
  $icon= explode( ',' , $attrTestValue ) ;

  foreach($icon as $icon_label)
  {?> 
  <!-- icon class  -->
  <a  href="
 <?php   $icon_url=$storeurl."".$icon_label;
 
 echo $iconurl = str_replace(' ', '', $icon_url);  ?>.html" class="<?php echo $icon_label;?>" title="<?php echo $icon_label;?>"  ><?php  echo $icon_label;?></a>
    
    <?php  } 

  }

  $sports = $_product->getResource()->getAttribute('sports_icon');
if($sports)
{
  $sports_attributeLabel=$sports->getStoreLabel($_product);
  ?>
  <span><?php echo $sports_attributeLabel; ?></span><br>
  <?php
  $Value = $sports->getFrontend()->getValue($_product);

$sports_icon= explode( ',' , $Value) ;

foreach($sports_icon as $data)
{?> 
<!-- icon class  -->
<a  href="
<?php   $sportsicon_url=$storeurl."".$data;
echo $sportsiconurl = str_replace(' ', '', $sportsicon_url);  ?>.html" class="<?php echo $data;?>" title="<?php echo $data;?>"  ><?php  echo $data;?></a>
 
  <?php  }

}
  // $_getMyAttr = $this->getProduct()->getAttributeText('product_icon');

$productId = $this->getProduct()->getAttributeText('product_id');
$productFactory = $objectManager->create('\Magento\Catalog\Model\ProductFactory');                            
$product        = $productFactory->create()->load($productId);
$attribute      = $product->getResource()->getAttribute('image');
$imageUrl       = $attribute->getFrontend()->getUrl($product);
$_product_url = $product->getProductUrl( $productId);
$myattribute1 = $_product->getResource()->getAttribute('short_desc_image_text')->getFrontend()->getValue($_product);
if($myattribute1):
?>
<a href="<?php echo $myattribute1;?>"> <?php echo $myattribute1;?></a>
<a href="<?php echo $_product_url;?>"> <?php echo '<img src="'.$imageUrl.'" />';?></a>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
<?php endif;?>
<script>

function isElementInViewport (el) {
      //special bonus for those using jQuery
      if (typeof jQuery === "function" && el instanceof jQuery) {
        el = el[0];
      }
      var rect = el.getBoundingClientRect();
      return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && /*or $(window).height() */
        rect.right <= (window.innerWidth || document.documentElement.clientWidth) /*or $(window).width() */
      );
    }


    // click-to-scroll behavior
    $("a").click(function (e) {
      e.preventDefault();
      var section = this.href;
      var sectionClean = section.substring(section.indexOf("#"));
      $("html, body").animate({
        scrollTop: $(sectionClean).offset().top
      }, 1000, function () {
        window.location.hash = sectionClean;
      });
    });
    
    // listen for the scroll event
    $(document).on("scroll", function() {
      //console.log("onscroll event fired...");
      // check if the anchor elements are visible
      $(".common").each(function (idx, el) {
        if ( isElementInViewport(el) ) {
          // update the URL hash
          if (window.history.pushState) {
            var urlHash = "#" + $(el).attr("id");
			window.history.pushState(null, null, urlHash);
          }
        }
      });
    });


</script>