<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <?php 


$product_Id = $_product->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockInfo = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($product_Id);
$stockqty = (int)$stockInfo->getQty();

$qty = (int)$stockInfo->getMaxSaleQty();?>
 

                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                            echo __('Qty') ?></span></label>
                    <div class="control control-qty-cart">
                    <select name="qty" id="qty" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" 
            class="qty-default qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                   <?php $i = 1 ; ?>
                    <?php while( $i <= $qty) { ?>
                  <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                <?php $i++; }?>                   

            </select>

                        <div class="control-qty">
                            <!-- <span class="quantity-controls quantity-plus"></span>
                            <span class="quantity-controls quantity-minus"></span> -->

                            <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $('.quantity-plus').click(function () {
                                        $('.qty-default').val(Number($('.qty-default').val()) + 1);
                                    });

                                    $('.quantity-minus').click(function () {
                                        var value = Number($('.qty-default').val()) - 1;
                                        if (value > 0) {
                                            $('.qty-default').val(value);
                                        }

                                    });
                                });
                            </script>
                        </div>
                    </div>


                    
                </div>


                
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */
                    echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (!$block->isRedirectToCartEnabled()) : ?>





    <?php
$date = $_product->getData('expire_date');
if($date): 
$servings = $this->getProduct()->getAttributeText('servings'); 
$newDate = date("d-m-Y", strtotime($date));
?>
<span> Before:<?php echo $newDate;?> | Servings:<?php echo $servings?> </span>

<?php
endif; ?>

<?php if ($_product->getIsSalable()): ?>
    <div class="stock available"><span><?php /* @escapeNotVerified */
       echo __('In stock. Immediate delivery.
       ') ?></span></div>                                           
   
     <?php else: ?>
       <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
        echo __('Out of stock') ?></span></div>
     <?php endif; ?>



   
  <!-- Button trigger modal -->
<span  data-toggle="modal" data-target="#exampleModalCenter">
Warning about our product information
</span>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><?php

$_getMyAttr = $_product->getResource()->getAttribute('product_warning');

if($_getMyAttr)

{
   echo $product_information_title=$_getMyAttr->getStoreLabel($_product);


 }?>



        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
    <?php  $_getMyAttr = $_product->getResource()->getAttribute('product_warning');

if($_getMyAttr)

{
    $product_warning_details = $_getMyAttr->getFrontend()->getValue($_product);
?>
<p><?php echo $product_warning_details; ?></p>
<?php
 }?>

      </div>
    
    </div>
  </div>
</div>





    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    
    </script>
<?php endif; ?>

<!-- Modal -->



  