<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>

<?php 
 $res1 = $this->getProduct()->getAttributeText('related_info_tab');
if($res1 == 'Yes'):
if($video_block = $this->getProduct()->getAttributeText('related_info_video_block')):?>
    <h4>VIDEOS RELATED TO <?php echo $_product->getName();?></h4>
<?php
    foreach(explode(",",$video_block) as $video):
  echo $this->getLayout()
  ->createBlock('Magento\Cms\Block\Block')
  ->setBlockId($video)
  ->toHtml();
endforeach;
  endif;

  if($image_block = $this->getProduct()->getAttributeText('related_info_image_block')): ?>
       <h4>BLOG ENTRIES RELATED TO <?php echo $_product->getName();?></h4>
<?php
    foreach(explode(",",$image_block) as $image):
  echo $this->getLayout()
  ->createBlock('Magento\Cms\Block\Block')
  ->setBlockId($image)
  ->toHtml();
endforeach;
  endif;
endif; ?>