<?php
    $product = $block->getProduct();
   $res1 = $this->getProduct()->getAttributeText('external_lab_analysis_tab');
    if($res1 == 'Yes'): 
if($lab_block = $this->getProduct()->getAttributeText('lab_analysis_block')):?>
<h4>In this section you can see and download the research carried out by independent certified laboratories, providing the most precise and detailed information of each one.</h4>
<?php
    foreach(explode(",",$lab_block) as $lab):
  echo $this->getLayout()
  ->createBlock('Magento\Cms\Block\Block')
  ->setBlockId($lab)
  ->toHtml();
endforeach;
  endif;
endif;
?>
