<?php use Magento\Framework\App\Action\Action; 

$productLabelHelper = $this->helper(Sparsh\ProductLabel\Helper\ProductLabelHelper::class);
$_config            = $this->helper('Sm\Market\Helper\Data');
$image_url=$block->getViewFileUrl('Magebees_Featuredproduct::images/ajax_loader.gif');
$unique_slider_key = $block->getUniqueSliderKey();
$fp_slider_id="magebees-featured-slider-".$unique_slider_key;
$fp_content_id="cwsFeaturedProducts-".$unique_slider_key;
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

	<div class="cwsFeatured" id="<?php echo $fp_content_id;?>">
		<div id="fp_scroll_loading" style="display:none;"><img src="<?php echo $image_url; ?>" alt="Loading..." /></div>
		<?php if($this->getShowHeading()): ?>
			<div class="title"><h3><?php echo __($this->getHeading()) ;?></h3></div>
		<?php endif; ?>
		<?php
			$_products = $this->getProductCollection();			
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
   
			$viewMode = 'grid';
			$image = 'category_page_grid';
			$showDescription = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			
			/*** Position for actions regarding image size changing in vde if needed */
			$pos = $block->getPositioned();
			$position = '';
			if ($pos != null) {
				$position = ' style="left:'.$block->getVar("{$image}:width").'px;'.'top:'.$block->getVar("{$image}:height").'px;"';
			}
		?>
		<?php if($this->getShowSlider()):?>
			<div id="cwsFpSlider" class="mage-featured-slider <?php /* @escapeNotVerified */ echo $viewMode; ?> products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
		<?php else: ?>
			<div class="<?php if(!$this->getAjaxscrollPage()) {?>auto_load_featured<?php }?> products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?> grid<?php echo $this->getProductsPerRow(); ?>">
		<?php endif; ?>
			<ol class="products list items product-items">
				<?php
					$iterator = 1;
					
					$i=0;?>
				<?php if($this->getShowSlider()):?>
				<div class="owl-carousel" id="<?php echo $fp_slider_id;?>">
					<?php endif; ?>
					<?php foreach ($_products as $_product):?>
				<?php  echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info" data-container="product-grid">
						<?php $productImage = $block->getImage($_product, $image);?>
						<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1"><?php echo $productImage->toHtml(); ?></a>


                           <!--LABEL PRODUCT-->
						 <?php
                            $orgprice = (float)$_product->getPrice();
                            $fnPrice  = (float)$_product->getFinalPrice();
                            $getSpecialPrice = (float)$_product->getSpecialPrice();

                            if ($_config->getAdvanced('show_salelabel')) {
                                if ($fnPrice < $orgprice) { ?>
                                    <div class="label-product label-sale">
									<span class="sale-product-icon">
										<?php echo __('Sale'); ?>
									</span>
                                    </div>
                                <?php }
                            }
                            ?>

                            <?php
                            $now      = date("Y-m-d");
                            $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                            $newsTo   = substr($_product->getNewsToDate(), 0, 10);


                            if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                    <div class="label-product label-new">
                                        <span class="new-product-icon"><?php echo __('New'); ?></span>
                                    </div>
                                <?php }
                            } ?>
                            <!--END LABEL PRODUCT-->

						<div class="product details product-item-details">
							<div style="padding: 0 2px;"><?php echo $block->getProductDetailsHtml($_product); ?></div>
							<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
							<strong class="product name product-item-name"><a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></strong>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>


					<?php
							$productLabelType = $productLabelHelper->getProductLabelType($_product);
							if (!empty($productLabelType)) 
							{
								if($productLabelType == 'text') 
								{
									$productLabel = $productLabelHelper->getProductLabel($_product);$productLabelColor = $productLabelHelper->getProductLabelColor($_product);
									$productLabelBackgroundColor = $productLabelHelper->getProductLabelBackgroundColor($_product);
								$productLabelShape = $productLabelHelper->getProductLabelShape($_product);
								if ($productLabel && $productLabelShape) 
								{ ?>
								<span class="sparsh-product-label"<?php echo !empty($productLabelColor) ? 'data-color=' . $productLabelColor : ''; ?><?php echo !empty($productLabelBackgroundColor) ? 'data-background-color=' . $productLabelBackgroundColor : ''; ?><?php echo !empty($productLabelShape) ? 'data-shape=' . $productLabelShape : '' ?>><?php echo $block->escapeHtml($productLabel); ?></span><?php }} 
								elseif ($productLabelType == 'image') {$productLabelImage = $productLabelHelper->getProductLabelImage($_product);if ($productLabelImage) { ?><div class="sparsh-product-label-image"><img src="<?php echo $productLabelHelper->getProductMediaUrl() . $productLabelImage; ?>"></div><?php }}}

                    ?>


							<?php if($this->getProductsPrice()): ?>
								<?php echo $block->getProductPrice($_product) ?>
							<?php endif; ?>



							<?php 


								$percentage = 0;
								if ($orgprice > $fnPrice)
								{
									$percentage = ($orgprice - $fnPrice) * 100 / $orgprice;
									$saveprice = ($orgprice - $fnPrice); 
								}

								if ($percentage) 
								{
									echo  (int)$percentage ; 
									echo "%";
								if($saveprice)
								{   
									echo "save!";
									echo $saveprice; 
								}

								}


								?>

							<div class="product-item-inner">
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<?php if($this->getAddToCart()): ?>
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
									<?php endif; ?>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" data-mage-init='{"validation":{}}'>
												<input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo        $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												 <?php echo $block->getBlockHtml('formkey')?>
												<?php if (($_product->isSaleable())&&($this->getAddToCart())):?>
													<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary"> <span><?php echo __('Add to Cart') ?></span> </button>
												<?php endif; ?>
												<?php
                                                    if($_product->isAvailable())
                                            
                                            {
                                                echo"In stock. Immediate delivery.";
                                            }
                                            
                                            ?>

											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
										<?php if($this->getAddToCart()): ?>
											</div>
										<?php endif; ?>
										<?php if($this->getAddToWishlist() || $this->getAddToCompare()): ?>
											<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
												<?php if($this->getAddToWishlist()): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
														<a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" data-post='<?php echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button"><span><?php echo __('Add to Wishlist') ?></span></a>
													<?php endif; ?>
												<?php endif; ?>
												<?php if($this->getAddToCompare()): ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
													<a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>' role="button"><span><?php echo __('Add to Compare') ?></span></a>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
									<?php if(!$this->getShowSlider()):?>
										<?php if ($this->getDescription()):?>
											<div class="product description product-item-description">
												<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="action more"><?php echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
						</div>
						</div>
					<?php echo($iterator == count($_products)+1) ? '</li>' : '' ?>
				<?php endforeach; ?>
					<?php if($this->getShowSlider()):?>
					</div>
				<?php endif; ?>
			</ol>
			</div>
	<?php if(!$this->getShowSlider()):?>
		<div class="mageFeaturedToolbar toolbar bottom"> <?php echo $block->getPagerHtml();  ?></div>
	<?php endif; ?>
	<?php if($this->getShowSlider())?>
		<?php 
		$navigation=$this->getNavarrow()=='1' ? 'true':'false';				
		$autoplay=$this->getAutoscroll()=='1' ? 'true':'false';	
		$slider_id=$fp_slider_id;
		?>				
		<?php else: ?>
		<?php
			$navigation="";
			$autoplay="";
			$slider_id="";			
		?>	
	<?php endif; ?>	
		<script type="text/javascript">
		requirejs([
			'jquery',
			'magebeesFeatured'				
		], function ($) {	
			var fp_content_id="<?php echo $fp_content_id;?>";
			var product_count="<?php echo $_products->count();?>";
			var widget = $('#'+fp_content_id).magebeesFeatured({
				"nav":"<?php echo $navigation; ?>",	
				"product_count":product_count,
				"autoplay":"<?php echo $autoplay; ?>",
				"slider_id":"<?php echo $slider_id; ?>"
			});						
		});	
		</script>	
<!--</div>-->
	</div>
 	   <?php if (!$block->isRedirectToCartEnabled()) : ?>
       <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>

